id = "material-icon-theme-fork"
name = "Material Icon Theme"
version = "0.1.3"
schema_version = 1
authors = ["deltabrain <github.com/deltabrain>"]
description = "Material Design icons."
repository = "https://github.com/deltabrain/material-icon-theme"
